import type { Handler } from '@netlify/functions'
import { createClient } from '@supabase/supabase-js'
import { rowToCampaign } from '../../src/types'

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const CORS = {
  'Content-Type': 'application/json',
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PATCH, DELETE, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
}

export const handler: Handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') return { statusCode: 204, headers: CORS, body: '' }

  const rawPath = event.path.replace(/\/.netlify\/functions\/campaigns\/?/, '')
  const parts = rawPath.split('/').filter(Boolean)
  const id = parts[0]
  const method = event.httpMethod

  try {
    // LIST campaigns (optional filters: ?channelId=<uuid>  ?status=active|paused|ended)
    if (method === 'GET' && !id) {
      const channelId = event.queryStringParameters?.channelId
      const status    = event.queryStringParameters?.status

      let query = supabase
        .from('campaigns')
        .select('*')
        .order('created_at', { ascending: false })

      if (channelId) query = query.eq('channel_id', channelId)
      if (status)    query = query.eq('status', status)

      const { data, error } = await query
      if (error) throw error
      return { statusCode: 200, headers: CORS, body: JSON.stringify((data ?? []).map(rowToCampaign)) }
    }

    // GET single campaign
    if (method === 'GET' && id) {
      const { data, error } = await supabase
        .from('campaigns')
        .select('*')
        .eq('id', id)
        .single()
      if (error) throw error
      return { statusCode: 200, headers: CORS, body: JSON.stringify(rowToCampaign(data)) }
    }

    // CREATE campaign
    if (method === 'POST') {
      const body = JSON.parse(event.body ?? '{}')
      if (!body.name || !body.channelId || !body.campaignType) {
        return { statusCode: 400, headers: CORS, body: JSON.stringify({ error: 'name, channelId, and campaignType are required' }) }
      }
      const { data, error } = await supabase
        .from('campaigns')
        .insert({
          channel_id:      body.channelId,
          name:            body.name,
          status:          body.status          ?? 'active',
          start_date:      body.startDate       ?? null,
          end_date:        body.endDate         ?? null,
          budget:          body.budget          != null ? Number(body.budget) : null,
          utm_source:      body.utmSource       ?? null,
          utm_medium:      body.utmMedium       ?? null,
          utm_campaign:    body.utmCampaign     ?? null,
          destination_url: body.destinationUrl  ?? null,
          campaign_type:   body.campaignType,
          // redirect_token auto-generated by DB default
        })
        .select()
        .single()
      if (error) throw error
      return { statusCode: 201, headers: CORS, body: JSON.stringify(rowToCampaign(data)) }
    }

    // UPDATE campaign
    if (method === 'PATCH' && id) {
      const body = JSON.parse(event.body ?? '{}')
      const updates: Record<string, unknown> = {}
      if (body.channelId      !== undefined) updates.channel_id      = body.channelId
      if (body.name           !== undefined) updates.name            = body.name
      if (body.status         !== undefined) updates.status          = body.status
      if (body.startDate      !== undefined) updates.start_date      = body.startDate
      if (body.endDate        !== undefined) updates.end_date        = body.endDate
      if (body.budget         !== undefined) updates.budget          = body.budget != null ? Number(body.budget) : null
      if (body.utmSource      !== undefined) updates.utm_source      = body.utmSource
      if (body.utmMedium      !== undefined) updates.utm_medium      = body.utmMedium
      if (body.utmCampaign    !== undefined) updates.utm_campaign    = body.utmCampaign
      if (body.destinationUrl !== undefined) updates.destination_url = body.destinationUrl
      if (body.campaignType   !== undefined) updates.campaign_type   = body.campaignType

      const { data, error } = await supabase
        .from('campaigns')
        .update(updates)
        .eq('id', id)
        .select()
        .single()
      if (error) throw error
      return { statusCode: 200, headers: CORS, body: JSON.stringify(rowToCampaign(data)) }
    }

    // DELETE campaign
    if (method === 'DELETE' && id) {
      const { error } = await supabase.from('campaigns').delete().eq('id', id)
      if (error) throw error
      return { statusCode: 204, headers: CORS, body: '' }
    }

    return { statusCode: 405, headers: CORS, body: JSON.stringify({ error: 'Method not allowed' }) }
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    return { statusCode: 500, headers: CORS, body: JSON.stringify({ error: message }) }
  }
}
